### ISSUE TITLE
Security Concerns with SDK V2

### ISSUE THREAD

**Issue by DevangML** [bcnmy/biconomy-client-sdk#242]
**Description**
The current implementation of the new SDK requires supplying API keys on the client-side using environment variables, especially in Next.js. This approach poses potential security risks since the keys are bundled with the JavaScript code during production, making them accessible to users.

**Suggestions**
I propose migrating the following processes to the server-side to enhance security and prevent exposure of sensitive information:

**_Bundler Migration:_** Move the bundler logic to the server-side to avoid exposing API keys to the client.

**_Paymaster Migration:_** Transfer the paymaster functionality to the server-side to ensure the secure handling of payment-related tasks.

**_Smart Account Creation on Server-Side:_** Implement smart account creation on the server-side to prevent the need for sending the JsonRpcSigner to the backend, which can introduce security vulnerabilities.

**Current Limitations**
At present, we encounter the following limitations:

**_JsonRpcSigner:_** The JsonRpcSigner cannot and should not be sent to the backend. As a result, creating the smart account does not work in this manner.

**_API Key Access:_** Even if we pass the paymaster and bundler from the server to the frontend, the API keys can still be accessed, posing a security risk.

**Community Collaboration**
I urge the community to come together and brainstorm novel solutions to address these security concerns and improve the overall safety and privacy of the SDK implementation.

Let's collaborate to find a more secure approach that ensures the confidentiality of sensitive data and mitigates potential risks associated with the current client-side handling of API keys.

Thank you for your attention to this matter. Your contributions and ideas are highly appreciated. Together, we can make the SDK safer and more robust.

**Comment by cardosofelipe** [comment]
A way to achieve this could be to have a Custom Bundler implemented with a custom api (to nextjs ssr or other backend) call instead of direct calls with bundled api key. This way the biconomy api call could be done in complete secret, without exposing it in Frontend.

**Comment by alko89** [comment]
I was just exploring this as well. I peeked into the source code for the SDK and figured out the paymaster object is only used in `buildTokenPaymasterUserOp`, so you can safely move the paymaster logic to the to the BE:

 - create userop on the FE
 - send the userop to the BE, attach payment master data and send it back to the FE
 - send userop from the FE
 
 This works great for the paymaster part, except if you're using the `buildTokenPaymasterUserOp`
 
 I'm not sure how to handle this part for the bundler yet, seems SmartAccount is using it, so would have to dig into it a bit more. My idea would be to refactor the SDK to make it so that the `BiconomySmartAccount` would not require the bundler and/or paymaster objects and be only responsible for creating userops which can then be bundled separately.
